version: '3'

networks:
  service-network:

volumes:
  data-volume:

services:
  gymhunter:
    container_name: gymhunter
    image: gymhunter:latest
    ports:
      - "80:8080"
    networks:
      - service-network
    volumes:
      - data-volume:/mnt/gymhunter-data
    environment:
      - IFTT_KEY
      - GYMHUNTER_PASSWORD
      - GYMHUNTER_STORAGE_DIR=/mnt/gymhunter-data
      - GYMHUNTER_SCHEDULER=20 */5 * ? * *
      - TZ=Europe/Warsaw

